import { mysqlTable, varchar, serial, text, timestamp, int } from 'drizzle-orm/mysql-core';

export const users = mysqlTable('tbl_users', {
  id: int('user_id').primaryKey(),
  name: varchar('user_name', { length: 255 }).notNull(),
  username: varchar('user_username', { length: 25 }).notNull(),
  password: varchar('user_password', { length: 255 }),
  email: varchar('user_email', { length: 255 }),
  phone: varchar('user_phone', { length: 20 }),
  status: varchar('user_status', { length: 20 }).notNull(),
  type: varchar('user_type', { length: 100 }).notNull(),
});

export const customers = mysqlTable('tbl_customer', {
  id: serial('customer_id').primaryKey(),
  name: varchar('customer_name', { length: 100 }),
  contactName: varchar('customer_contact_name', { length: 100 }),
  phone: varchar('customer_contact_phone', { length: 50 }),
  email: varchar('customer_email', { length: 500 }),
  region: varchar('customer_status_group', { length: 50 }),
  implementationType: varchar('customer_implementation_type', { length: 20 }),
  vehicleCount: int('actual_veh_count').default(0),
  createdBy: varchar('customer_sales_person_id', { length: 150 }).default(''),
});

export const serviceRequests = mysqlTable('tbl_customer_services_beta', {
  id: serial('customer_service_id').primaryKey(),
  createdAt: varchar('customer_service_created_date', { length: 100 }),
  source: varchar('customer_service_created_by', { length: 100 }),
  region: varchar('region', { length: 100 }),
  status: varchar('customer_service_status', { length: 50 }).default('new'),
  implementationType: varchar('customer_service_customer_type', { length: 100 }),
  customerName: text('customer_service_customer_name'),
  contactName: varchar('customer_service_customer_contact_name', { length: 255 }),
  phone: varchar('customer_service_customer_phone', { length: 50 }),
  email: varchar('customer_service_customer_email', { length: 500 }),
  address: text('customer_service_customer_address'),
  mapLink: text('customer_service_address_map'),
  coordinates: varchar('customer_service_address_cordinates', { length: 100 }),
  
  newQty: int('customer_service_quantity').default(0),
  migrateQty: int('customer_service_quantity').default(0),
  tradingQty: int('customer_service_quantity').default(0),
  serviceQty: int('customer_service_quantity').default(0),
  otherQty: int('customer_service_quantity').default(0),
  accessories: text('schedule_note'),
  
  requestedPerson: varchar('requested_by', { length: 100 }),
  salesPerson: varchar('customer_service_L2_assigned_to', { length: 100 }),
  salesType: varchar('customer_service_status', { length: 100 }),
  
  projectValue: varchar('customer_service_amount', { length: 100 }),
  priceDetails: text('customer_service_payment'),
  comment: text('customer_service_description'),
  
  issueDescription: text('customer_service_description'),
  location: varchar('region', { length: 100 }),
  paymentStatus: varchar('customer_service_payment_status', { length: 50 }),
  amount: varchar('customer_service_amount', { length: 50 }),
  vehicleDetails: text('schedule_note'),
  notes: text('schedule_note'),
  jobStatus: varchar('customer_service_status', { length: 50 }).default('new'),
  createdBy: varchar('customer_service_created_by', { length: 150 }).default(''),
});

export const messages = mysqlTable('messages', {
  id: serial('id').primaryKey(),
  role: varchar('role', { length: 20 }).notNull(), // 'user' or 'assistant'
  content: text('content').notNull(),
  timestamp: timestamp('timestamp').defaultNow(),
  username: varchar('username', { length: 255 }),
});

export const salesplusEntries = mysqlTable('salesplus_entries', {
  id: serial('id').primaryKey(),
  synohubRequestId: int('synohub_request_id'),
  salesPlusId: int('sales_plus_id').default(0),
  salesPlusDate: varchar('sales_plus_date', { length: 20 }),
  salesPlusSource: varchar('sales_plus_source', { length: 100 }),
  salesPlusRegion: varchar('sales_plus_region', { length: 100 }),
  salesPlusStatus: varchar('sales_plus_status', { length: 50 }),
  salesPlusImplementationType: varchar('sales_plus_implementation_type', { length: 100 }),
  locatorPlan: varchar('locator_plan', { length: 100 }),
  salesPlusPrice: varchar('sales_plus_price', { length: 100 }),
  salesPlusProjectValue: varchar('sales_plus_project_value', { length: 100 }),
  salesPlusCompanyName: text('sales_plus_company_name'),
  salesPlusCustomerName: varchar('sales_plus_customer_name', { length: 255 }),
  salesPlusPhone: varchar('sales_plus_phone', { length: 50 }),
  salesPlusEmail: varchar('sales_plus_email', { length: 255 }),
  salesPlusDesignation: varchar('sales_plus_designation', { length: 255 }),
  salesPlusAddress: text('sales_plus_address'),
  salesPlusAddressMap: text('sales_plus_address_map'),
  salesPlusAddressCoordinates: varchar('sales_plus_address_coordinates', { length: 100 }),
  salesPlusPerson: varchar('sales_plus_person', { length: 50 }),
  salesPlusType: varchar('sales_plus_type', { length: 100 }),
  salesPlusQuantityNew: int('sales_plus_quantity_new').default(0),
  salesPlusQuantityMigrate: int('sales_plus_quantity_migrate').default(0),
  salesPlusQuantityTrading: int('sales_plus_quantity_trading').default(0),
  salesPlusQuantityService: int('sales_plus_quantity_service').default(0),
  salesPlusQuantityOthers: int('sales_plus_quantity_others').default(0),
  salesPlusSupplier: varchar('sales_plus_supplier', { length: 255 }),
  salesPlusAccessories: text('sales_plus_accessories'),
  salesPlusComment: text('sales_plus_comment'),
  salesPlusRequestedBy: varchar('sales_plus_requested_by', { length: 50 }),
  scheduleNote: text('schedule_note'),
  schedulePhone: varchar('schedule_phone', { length: 50 }),
  priority: varchar('priority', { length: 50 }),
  clientName: text('clientName'),
  itcUsername: varchar('itcUsername', { length: 255 }),
  itcPassword: varchar('itcPassword', { length: 255 }),
  projectImplementationType: varchar('projectImplementationType', { length: 100 }),
  leadType: varchar('leadType', { length: 100 }),
  tradeNumber: varchar('tradeNumber', { length: 100 }),
  notes: text('notes'),
  createNewNob: int('create_new_nob').default(0),
  existingCustomer: int('existing_customer').default(0),
  customerId: int('customer_id').default(0),
  additionalContactDetails: text('additional_contact_details'),
  synohubRequestedPerson: varchar('synohub_requested_person', { length: 100 }),
  createdAt: timestamp('created_at').defaultNow(),
});
